export const DEFAULT_REGIONS = [
  "us-east-1",
  "us-east-2",
  "us-west-2",
  "ca-central-1",
  "sa-east-1",
  "eu-west-1",
  "eu-west-2",
  "eu-central-1",
  "ap-southeast-2",
  "ap-northeast-1",
  "ap-northeast-2",
  "ap-south-1",
];

export const CATALOG = {
  Architect: [
    "genesyscloud_flow",
    "genesyscloud_flow_loglevel",
    "genesyscloud_flow_milestone",
    "genesyscloud_flow_outcome",
    "genesyscloud_architect_datatable",
    "genesyscloud_architect_datatable_row",
    "genesyscloud_architect_emergencygroup",
    "genesyscloud_architect_grammar",
    "genesyscloud_architect_grammar_language",
    "genesyscloud_architect_ivr",
    "genesyscloud_architect_schedules",
    "genesyscloud_architect_schedulegroups",
    "genesyscloud_architect_user_prompt",
  ],
  "Integrations and data actions": [
    "genesyscloud_integration",
    "genesyscloud_integration_action",
    "genesyscloud_integration_action_draft",
    "genesyscloud_integration_credential",
    "genesyscloud_integration_custom_auth_action",
  ],
  Routing: [
    "genesyscloud_routing_queue",
    "genesyscloud_routing_skill",
    "genesyscloud_routing_wrapupcode",
    "genesyscloud_routing_language",
    "genesyscloud_routing_email_domain",
    "genesyscloud_routing_email_route",
    "genesyscloud_routing_settings",
    "genesyscloud_routing_utilization",
    "genesyscloud_routing_utilization_label",
  ],
  "Authorization and organization": [
    "genesyscloud_auth_division",
    "genesyscloud_auth_role",
    "genesyscloud_group",
    "genesyscloud_group_roles",
    "genesyscloud_location",
    "genesyscloud_oauth_client",
    "genesyscloud_organization_authentication_settings",
    "genesyscloud_organization_presence_definition",
    "genesyscloud_user",
  ],
  "Scripts and response management": [
    "genesyscloud_script",
    "genesyscloud_responsemanagement_library",
    "genesyscloud_responsemanagement_response",
  ],
  Telephony: [
    "genesyscloud_telephony_providers_edges_site",
    "genesyscloud_telephony_providers_edges_phone",
    "genesyscloud_telephony_providers_edges_phonebasesettings",
    "genesyscloud_telephony_providers_edges_trunkbasesettings",
    "genesyscloud_telephony_providers_edges_did_pool",
    "genesyscloud_telephony_providers_edges_extension_pool",
  ],
  Outbound: [
    "genesyscloud_outbound_campaign",
    "genesyscloud_outbound_campaignrule",
    "genesyscloud_outbound_contact_list",
    "genesyscloud_outbound_contact_list_contact",
    "genesyscloud_outbound_contact_list_template",
    "genesyscloud_outbound_contactlistfilter",
    "genesyscloud_outbound_dnclist",
    "genesyscloud_outbound_ruleset",
    "genesyscloud_outbound_sequence",
    "genesyscloud_outbound_callanalysisresponseset",
    "genesyscloud_outbound_callabletimeset",
    "genesyscloud_outbound_attempt_limit",
    "genesyscloud_outbound_digitalruleset",
    "genesyscloud_outbound_messagingcampaign",
    "genesyscloud_outbound_settings",
    "genesyscloud_outbound_wrapupcode_mappings",
  ],
  "Knowledge and AI": [
    "genesyscloud_knowledge_knowledgebase",
    "genesyscloud_knowledge_category",
    "genesyscloud_knowledge_document",
    "genesyscloud_knowledge_document_variation",
    "genesyscloud_knowledge_label",
    "genesyscloud_ai_studio_summary_setting",
    "genesyscloud_intents_categories",
    "genesyscloud_intents_customerintents",
  ],
  "Quality, recording, and learning": [
    "genesyscloud_quality_forms_evaluation",
    "genesyscloud_quality_forms_survey",
    "genesyscloud_recording_media_retention_policy",
    "genesyscloud_employeeperformance_externalmetrics_definitions",
    "genesyscloud_learning_modules",
  ],
  Messaging: [
    "genesyscloud_conversations_messaging_integrations_apple",
    "genesyscloud_conversations_messaging_integrations_instagram",
    "genesyscloud_conversations_messaging_integrations_open",
    "genesyscloud_conversations_messaging_integrations_whatsapp",
    "genesyscloud_conversations_messaging_settings",
    "genesyscloud_conversations_messaging_supportedcontent",
  ],
  "Journey and guides": [
    "genesyscloud_journey_action_map",
    "genesyscloud_journey_action_template",
    "genesyscloud_journey_outcome",
    "genesyscloud_journey_outcome_predictor",
    "genesyscloud_journey_segment",
    "genesyscloud_journey_view_schedule",
    "genesyscloud_guide",
    "genesyscloud_guide_version",
  ],
  "External contacts and identity": [
    "genesyscloud_external_contacts_external_source",
    "genesyscloud_external_contacts_organization",
    "genesyscloud_idp_adfs",
    "genesyscloud_idp_generic",
    "genesyscloud_idp_gsuite",
    "genesyscloud_idp_okta",
    "genesyscloud_idp_onelogin",
    "genesyscloud_idp_ping",
    "genesyscloud_idp_salesforce",
  ],
  "Automation and business rules": [
    "genesyscloud_process_automation_trigger",
    "genesyscloud_business_rules_schema",
    "genesyscloud_business_rules_decision_table",
    "genesyscloud_case_management_caseplan",
    "genesyscloud_case_management_stageplan",
    "genesyscloud_case_management_stepplan",
  ],
  Other: [
    "genesyscloud_greeting",
    "genesyscloud_greeting_user",
    "genesyscloud_group_greeting",
    "genesyscloud_orgauthorization_pairing",
    "genesyscloud_platform",
    "genesyscloud_resource_cache",
    "genesyscloud_tf_export",
    "genesyscloud_bcp_tf_exporter",
  ],
};

export const ALL_RESOURCE_TYPES = Object.values(CATALOG).flat();
